project_name: domain-deploy

env:
  - GO111MODULE=on

builds:
  - env:
      - APP_NAME=domain-deploy
      - APP_VERSION=1.0.0
      - flags=-X main.appName=$(APP_NAME) -X main.appVersion=$(APP_VERSION) -X main.main.goVersion=$(go version) -X main.main.buildTime=`date -u '+%Y-%m-%d'` -X main.gitHash=`git show -s --format=%H`
      - CGO_ENABLED=0
    main: main/main.go
    binary: domain-deploy
    output: ./bin
    goos:
      - darwin
      - linux
      - windows
      - freebsd
    goarch:
      - amd64
      - 386
      - arm
      - arm64
      - riscv64
    goarm:
      - 5
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386
      - goos: freebsd
        goarch: arm

archives:
  - name_template: "{{.Os}}-{{.Arch}}{{if .Arm}}v{{.Arm}}{{end}}-{{ .ProjectName }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - ./bin/**